apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  containers:
    - name: writer
      image: busybox
      command: ["sh", "-c", "echo hello-from-$(hostname) > /data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: shared-rwx
